os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^master$/"
  - "/^pre-release$/"
  - "/^v.*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - BRANCH=${TRAVIS_BRANCH}
  - TAG=${TRAVIS_TAG}
  - DOCKERHUB='chalmersfsd'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: Pc7u5KdLhZKB5md0jY0uG4KYbfO4p6Yp5SNDQ0wsT9cnQ7Rd7Xe+b0687fCHkQxo7/WaW68J2Ns8tYYnakOqAygIf3udSx+rsoY6YAsxA/kGMjXMXlfi9NZbRfCT/OUNmReKwpqUCX8ZjOguCFOFBJzQAyjEZZI2KFwAA9BrCigQ3+UsZBbUcSiTxl0ZstHSM0cUyEvTM1M0rFPpJUY458VLrSY4W26Jw7+J0HEoN3TN6Mm2RPlejvQjwC7lH6mEt5zZNgWqm9A/TsVqAXLUEr0Hk6IxsBhiSGPI3/x/IVnXxb3LfQaAhqK+Pom24vnBnwmvjAOZsuWDo2FduddNrNmZ13pPJfO6wfvAvHSMZ6YzSw1lh4CI6obsLVaPO1CPIcrWaR1WUVCM7ur3/7cTb8uTrK9iQQGDZMyVA839NHwGYn9d7NX3dpumQzefqfViVqqo86sSf+8uXM0EbDhwOfIgFWk8V9bmNeRxZ2lfk2aN9QGsM9WhFEUtAL36qGMZQwbgwmYinpfoFhBWQ9YJr5ds9OYHkuWAfhqqqN99xTryBa6pICrgcrL+Jvpx733O51PPrEV9uxPoW3w91EbrSJoPgS2kBb5dmfO12gG8Uu1kRW77qET7I8S3mFfdOOwN8581ONBCh1hpJVOnOrzkVYnUm1i3a+ZF/RXPXZxG9W8=
  - secure: z7vQ4LPCI1W2RVnIOdOKknRzHfb0C/JuZaq2luPDsqkVvWlzAGGw6YX4o5BZ0XC4cxZHkpFPchht8KtHot7O/5c4xko+rvFF69/gbwAeqn70+hqsksOQYiQBvV6AYxagTmVvaT9PH4hOxzlMkVCQFpvx2ZX0EASNsE+4HqQPg3kXPfSj9NllfhqrEZBV6THCyVxgZ1th4w+fDt5wM7t+VGT9tdi06we4S3nXSBviQ5MnOf8pLVDQGhw3yTelO7UEe/COk4hF6UZdlwofYL8EA+6N2HKPRqKmnZmo/XpvrrSWhie7a/qQ8v3dmamWQwSDwhSfYcOwgTgxOKYdD4plwagPl0Tr8Dxvc6Ave7wg6aIQXTg9vzsrXvFmcLEc3VgCgOGxUPv8zE20s9Im4QGVZBPF3P1nwIqJVkDEre7Aae0BoTLde1poYi1evvr3YhJUThI1oRv8ZlrzlrfjCvZl/CbGt2OQC5iN0YRdWw3DZUsw4yUOSeFKPyuuXmuejkcfGVnRpXiAS4J9aZvDlgAxRFvSUJp4so3gwLNEyIREbyZ6VZbrDrm0DI2wSEoL8Unbnv1pbp3uo7MS6Hq5PakQpoGCTyU4n+L6X2SmdQdwJWoXZllcZCugdru0fxZd3SOKDMa5B+XE1IO+pVH/VQqWFyJzSXqQ2UGhARWt8zrMVcc=
install:
- docker build -f Dockerfile.amd64 -t ${IMAGE}:${BRANCH} .
script: skip
after_success:
- if [[ -z "${TAG}" ]]; then echo "This commit hasn't been tagged, will not be pushed
  to dockerhub"; exit 0; fi
- docker --version
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker tag ${IMAGE}:${BRANCH} ${DOCKERHUB}/${IMAGE}:${TAG}
- docker push ${DOCKERHUB}/${IMAGE}:${TAG}
- echo "${DOCKERHUB}/${IMAGE}:${TAG}"
notifications:
  email:
    on_success: never
    on_failure: never
