os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^test.*$/"
  - "/^v[0-9].*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - DOCKERHUB='chalmersfsd'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: i7qZoBSnn/mFDsU10Z5/ZtDq4c/r0dGev3xe+0ywrchw/PF8zgzeeaL1gmZs8UI6xZIlFXne9Hle0rjFIkqQppHImhWZw8V8FQ7RyyCQ9/GfjtUEHSN1eX9zH7SkWQXxbXYfCmzPupCOmUrM07GeVfHfOKchIAeSa9Yf/CiOo8vgDD5wpPg6iNki/5TBAzZ3+O4Hz4QPSYfhByeRIQGPgLQpOs4wTbTy1ZE+7/TqRqoRANp9k0LCYADZ6sEXS2KBlnhslDbn5s+bsO8X+spRIUALsig5zmE83JQEzR3beQeJraaf1PJ9QuST7QZtxq4KpsWsmWOhLZS/lA1IdRz4MUGJl7vXS/dDK3vZPyJwzxOgNYTfPN8t3Gp4remhFoPfd3zerrZveWP9eTWbvlVcTS1VJm99/vJnmHrLj2F0Sf0uZ/6lBDVRz2UiKHceLdFZ/h672nAuz1yZfCwfWue57Fq/JKoLZ25B2S8NFL0ohEi510H4aaLUgX6VtQsacb76EfVwqyGfrVAXPVg91+k5YhgV+jEkLvFYsM6xJtMOtdjddh9Z90mCFezZFepFidM7X2qLCijFy4IL0ucVQULqaE3N5Iwvo5hOTzO/szck9mW347dxyewcGcHxUTnwzHsPtGaehTx6tXiqCVIpsbL+grswfjq2UiZCE3UgzpEURLs=
  - secure: ZSz0fZGFpt5h/HLhVxc1DIGew4wIUQcwV5LIEfmN2P6TvKm4ic3vpSDibnYwSi7qJE5y6/KHjCsXN1rnPMpWo1LFewdLacV1gRcMqRWnmFJr0SLF4a3v87dS5C/I0cPAeLbTAoeh/B5Y/oLhdHGnfKC1/s2qiZjJomv8qFQgwXZ5u1U107JzYs44cZrJU4w6MY/B4ocn0+MPi9fy3q3czkU06MmGT4NPAWm7LjspXJ2bRSAsj01b1VcZmsSOGPQriY9a4aiMMKUrsAqMkf6crm1C6McOS/FBlq5qnTgHuUbrW6+pP1m6TizNNqJjdBHkGtRhng/U2TApYOf7oIor1r/Mi+itPJKN9URYb/6s81b5zkU8Te4jMbyXmdDqaogOIUKN63SEUZzqReF3Jn4tezFkQg6nnRB6n4u5muFAyHo1tu14QHPxT1uPf8V8SeifioaxN625YLZv7Yubmv4nS0od6rVEuvqAkqKn5OqrDqyvCNUi/2q+E22BVj8je7+mwN6GWgrVf8G4jzkdDfzof+aNseT18nuwEZyfvKMQjJwBhvPSH0ZQk/rfcPXS6M27CQejBjLXZSiAR/+volVjsjkS/J5AXrpfx4EMOyQUI0vcd2f873CBhH3ooDjZgBz3yuuooD3DAkHGXUTzuQN7ZPgnGgX9a8RbEHo8RRSaQLo=
install:
- docker build -f Dockerfile.amd64 -t ${IMAGE} .
script: skip
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- if [[ "${TRAVIS_BRANCH}" == *test* ]]; then docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER};
  docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}; echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}";
  else docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}; docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH};
  echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}"; fi
notifications:
  email:
    on_success: never
    on_failure: never
